<?php
require_once __DIR__ . '/layout/head.phtml';
?>

<body class="d-flex align-items-center py-4 bg-body-tertiary">
	<main class="form-signin w-100 m-auto">
		<form action="" method="post">
			<!-- <img class="mb-4" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57"> -->
			<h1 class="h3 mb-3 fw-normal">Please sign in</h1>
			<div class="form-floating">
				<input type="text" class="form-control" id="login" name="login" placeholder="login">
				<label for="login">login</label>
			</div>
			<div class="form-floating">
				<input type="password" class="form-control" id="password" name="password" placeholder="password">
				<label for="password">password</label>
			</div>
			<button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
		</form>
	</main>
</body>

<style>
	html,
	body {
		height: 100%;
	}

	.form-signin {
		max-width: 330px;
		padding: 1rem;
	}

	.form-signin .form-floating:focus-within {
		z-index: 2;
	}

	.form-signin input[type="email"] {
		margin-bottom: -1px;
		border-bottom-right-radius: 0;
		border-bottom-left-radius: 0;
	}

	.form-signin input[type="password"] {
		margin-bottom: 10px;
		border-top-left-radius: 0;
		border-top-right-radius: 0;
	}
</style>

<?php
require_once __DIR__ . '/layout/foot.phtml';
?>