<?php

use model\Mdl;

$f3 = Base::instance();
$TIME = $f3->get("TIME");
$controller_duration = microtime(true) - $TIME;

$db_logs_parsed = Mdl::parseDbLogs();
?>
	<footer class="footer">
		<div class="container">
			<span class="text-muted">
				generation time : <?= round($controller_duration*1000, 3) ?> ms
				| 
				<?= count($db_logs_parsed) ?> SQL queries : <?= array_sum($db_logs_parsed) ?> ms
			</span>
		</div>
	</footer>
