	<header>
		<!-- Fixed navbar -->
		<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary">
			<div class="container-fluid d-flex justify-content-between">
				<a class="navbar-brand" href="<?= $BASE . $f3->alias("homepage") ?>">Music library handler</a>
				<button class="navbar-toggler" type="button"
					data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
					aria-controls="navbarCollapse" aria-expanded="false"
					aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				
				<div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
					<ul class="navbar-nav">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Bulk </a>
							<ul class="dropdown-menu dropdown-menu-dark bg-primary">
								<li><a class="dropdown-item" href="<?= $BASE . $f3->alias("bulk_rename") ?>">rename</a></li>
							</ul>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Ampache </a>
							<ul class="dropdown-menu dropdown-menu-dark bg-primary">
								<li><a class="dropdown-item" href="<?= $BASE . $f3->alias("ampache_stats") ?>">stats</a></li>
								<li><a class="dropdown-item" href="<?= $BASE . $f3->alias("ampache_navigate") ?>">navigate</a></li>
								<li><a class="dropdown-item" href="<?= $BASE . $f3->alias("ampache_albumCompare") ?>">album compare</a></li>
								<li><a class="dropdown-item" href="<?= $BASE . $f3->alias("ampache_codecs") ?>">codecs</a></li>
							</ul>
						</li>
					</ul>
				</div>
				
				<span>
					<?= $SESSION ["auth"] ["user"] ["fullname"] ?>
					<a class="btn btn-danger" title="logout" href="<?= $BASE . $f3->alias("logout") ?> ">
						<i class="fa-solid fa-right-from-bracket"></i>
					</a>
				</span>
			</div>
		</nav>
	</header>