<?php

use classes\Stuff;
use DB\CortexCollection;

require_once __DIR__.'/../layout/head.phtml';
?>

<?php
require_once __DIR__.'/../layout/header.phtml';
?>

	<main role="main" class="container-fluid bg-info">
		<form action="" method="get" class="d-flex justify-content-between pb-1">
			<div class="row g-3 align-items-center">
				<div class="col-auto">
					<label for="src_catalog_id" class="col-form-label">source catalog</label>
				</div>
				<div class="col-auto">
					<select class="form-select" name="src_catalog_id">
						<option value=""></option>
						<?php
						foreach ($catalogs_by_id as $catalog) {
							?>
							<option value="<?= $catalog->id ?>" <?= ($catalog->id == $f3->get("REQUEST.src_catalog_id")) ? "selected" : "" ?>><?= $catalog->name ?></option>
							<?php
						}
						?>
					</select>
				</div>
				
				<div class="col-auto">
					<i class="fa-solid fa-right-long"></i>
				</div>

				<div class="col-auto">
					<label for="dest_catalog_id" class="col-form-label">destination catalog</label>
				</div>
				<div class="col-auto">
					<select class="form-select" name="dest_catalog_id">
						<option value=""></option>
						<?php
						foreach ($catalogs_by_id as $catalog) {
							?>
							<option value="<?= $catalog->id ?>" <?= ($catalog->id == $f3->get("REQUEST.dest_catalog_id")) ? "selected" : "" ?>><?= $catalog->name ?></option>
							<?php
						}
						?>
					</select>
				</div>

				<div class="col-auto">
					<button class="btn btn-success" type="submit"><i class="fa-solid fa-not-equal"></i> compare</button>
				</div>
			</div>
			<div class="">
				<button class="btn btn-danger" type="submit" form="form-select-songs"><i class="fa-solid fa-file-export"></i> convert</button>
			</div>
		</form>
	</main>
	
	<?php
	if(!empty($albums_by_artist)) {
		$src_catalog = $catalogs_by_id [$f3->get("REQUEST.src_catalog_id")];
		?>
		<main role="main" class="container-fluid">
			<form action="" method="post" id="form-select-songs">
				<ul>
					<li>
						<input type="checkbox" class="form-check-input" style="" id="catalog[<?= $src_catalog->id ?>]" name="catalog[<?= $src_catalog->id ?>]">
						<label for="catalog[<?= $src_catalog->id ?>]">
							<i class="fa-solid fa-book"></i>
							<span title="<?= $src_catalog->catalogLocal->path ?>"><?= $src_catalog-> name ?></span>
						</label>
					</li>
					<ul>
						<?php
						foreach ($albums_by_artist as $artist_id => $albums) {
							$artist = $artists [$artist_id];
							?>
							<li>
								<input type="checkbox" class="form-check-input" style="" id="artist[<?= $artist->id ?>]" name="artist[<?= $artist->id ?>]">
								<label for="artist[<?= $artist->id ?>]">
									<i class="fa-solid fa-people-group"></i>
									<?= $artist -> prefix ?> <?= $artist -> name ?>	
								</label>
							</li>
							<ul>
								<?php
								$albums = CortexCollection::factory($albums);
								$albums->orderBy("year ASC");
								foreach ($albums as $album) {
									?>
									<li>
										<input type="checkbox" class="form-check-input" style="" id="album[<?= $album->id ?>]" name="album[<?= $album->id ?>]">
										<label for="album[<?= $album->id ?>]">
											<i class="fa-solid fa-record-vinyl"></i>
											(<?= $album -> year ?>) <?= $album -> name ?>
										</label>
										<a class="album-songs-toggle text-black text-decoration-none" id="album-toggle[<?= $album->id ?>]" type="menu">
											<i class="fa-solid fa-chevron-up rotate-reset"></i>
										</a>
									</li>
									<ul style="display: none;">
										<?php
										$songs = $album->songs; /** @var CortexCollection $songs */
										$songs->orderBy("track ASC");
										foreach ($songs as $song) {
											?>
											<li>
												<input type="checkbox" class="form-check-input" style="" id="song[<?= $song->id ?>]" name="song[<?= $song->id ?>]">
												<label for="song[<?= $song->id ?>]">
													<i class="fa-solid fa-music"></i>
													<span title="<?= $song->file ?>"><?= $song->track ?> : <?= $song->title ?></span>
													(<?= Stuff::secondesToDurationString($song->time) ?>) [<?= $song->mode ?> <?= intdiv($song->bitrate, 1024) ?> kB/s] <?= intdiv($song->size, 1024*1024) ?> MB
												</label>
											</li>
											<?php
										}
										?>
									</ul>
									<?php
								}
								?>
							</ul>
							<?php
						}
						?>
					</ul>
				</ul>
			</form>
		</main>
		<?php
	}
	?>
	
	
<?php
require_once __DIR__.'/../layout/footer.phtml';
?>

<?php
require_once __DIR__.'/../layout/foot.phtml';
?>

<style>
	.rotate {
		transform: rotate(180deg);
		transition: .3s;
	}
	.rotate-reset {
		transform: rotate(0deg);
		transition: .3s;
	}
</style>

<script language="javascript">
	$(function(){
		
		// propagate checkbox status to sons
		$("input[type=checkbox]").on("change", function(){
			var id = $(this).attr("id");
			var status = $(this).is(':checked');
			var list = $(this).parent("li").next("ul");
			list.find("input[type=checkbox]").each(function(){
				$(this).prop("checked", status);
			});
		});
		
		// toggle album songs display
		$(".album-songs-toggle").on("click", function(){
			$(this).children("i").toggleClass('rotate');
			$(this).children("i").toggleClass('rotate-reset');
			var songs_list = $(this).parent("li").next("ul");
			songs_list.slideToggle(300);
		});
		
	});
</script>
