<?php

use model\Catalog;

require_once __DIR__.'/../layout/head.phtml';
?>

<?php
require_once __DIR__.'/../layout/header.phtml';
?>

	<main role="main" class="container-fluid bg-info">
		<form action="" method="get">
			<div class="row g-3 align-items-center">
				<div class="col-auto">
					<label for="src_catalog_id" class="col-form-label">source catalog</label>
				</div>
				<div class="col-auto">
					<select class="form-select" name="src_catalog_id">
						<option value=""></option>
						<?php
						foreach ($catalogs as $catalog) {
							?>
							<option value="<?= $catalog->id ?>" <?= ($catalog->id == $f3->get("REQUEST.src_catalog_id")) ? "selected" : "" ?>><?= $catalog->name ?></option>
							<?php
						}
						?>
					</select>
				</div>
				
				<div class="col-auto">
					<i class="fa-solid fa-right-long"></i>
				</div>

				<div class="col-auto">
					<label for="dest_catalog_id" class="col-form-label">destination catalog</label>
				</div>
				<div class="col-auto">
					<select class="form-select" name="dest_catalog_id">
						<option value=""></option>
						<?php
						foreach ($catalogs as $catalog) {
							?>
							<option value="<?= $catalog->id ?>" <?= ($catalog->id == $f3->get("REQUEST.dest_catalog_id")) ? "selected" : "" ?>><?= $catalog->name ?></option>
							<?php
						}
						?>
					</select>
				</div>

				<div class="col-auto">
					<button class="btn btn-success" type="submit">compare</button>
				</div>
			</div>
		</form>
	</main>
	
	<main role="main" class="container-fluid">
		<ul>
			<?php
			foreach ($albums_by_artist as $artist_id => $albums) {
				?>
				<li><?= $artists [$artist_id] -> name ?></li>
				<ul>
					<?php
					foreach ($albums as $album) {
						?>
						<li><?= $album -> name ?></li>
						<?php
					}
					?>
				</ul>
				<?php
			}
			?>
		</ul>
	</main>
	
<?php
require_once __DIR__.'/../layout/footer.phtml';
?>

<?php
require_once __DIR__.'/../layout/foot.phtml';
?>
